### PR TITLE
Background Before Opacity reduced

### PR DESCRIPTION
**Pull request by Abdulkader69**

### CODE REVIEW

**Comment by vitaliybaran** [comment]
yes, demo server
nothing changed
plugin

**Comment by jibon57** [comment]
@vitaliybaran what you're expecting to have? Also send us the background image that you've updated in Moodle.

**Comment by vitaliybaran** [comment]
I am expecting to have this (That's what it was before the update)
Vidlessonbackground2

**Comment by vitaliybaran** [comment]
and this is my Moodle
plugin2

**Comment by vitaliybaran** [comment]
the image is shadowed both on the remote client and locally downloaded client

**Comment by Abdulkader69** [comment]
@vitaliybaran 
We used some gray color overlay before the custom image because some users use light images.
we think you can use any light background image. Your image and our overlay are the same color that's why it's happening.

**Comment by vitaliybaran** [comment]
Your overlay is definitely too much dark. I used several very light images and it still looks awful. Why not tell the users to upload the right image as a background instead of creating a problem with adjusting background images and also logos to match your dark overlay. I just do not see any logic behind this.

**Comment by Abdulkader69** [comment]
@vitaliybaran thanks we will fix it. wait a moment.

**Comment by jibon57** [comment]
@vitaliybaran issues fixed in this PR: https://github.com/mynaparrot/plugNmeet-client/pull/188
You can try demo site again

**Comment by vitaliybaran** [comment]
Now it's perfect on the remote client. Local client is still with overlay.

**Pull request merged**
