### PR TITLE
Update waitingRoomPage.tsx

### PR DESCRIPTION
**Pull request by oksuzgil**
Waiting room logo added

### CODE REVIEW

**Comment by jibon57** [comment]
Thanks for the PR. You didn't need to open 3 PRs for thid purpose. Only 1 was enough. Also you didn't add fallback default logo which will break existing system.

**Comment by oksuzgil** [comment]
Hello jibon, what I wanted to do was to send exactly one post, but I didn't know how to do it, so I sent it separately. I didn't want to tire you out by contacting you about this. I tried to send about the logo, but I couldn't. It will be enough to just change the normal logo file and drop it into the relevant folder. Only the user who wants to change can continue by making changes. Those who do not change it continue with the same logo. I would like to help with minor adjustments. I don't want to get tired in this process.

**Comment by jibon57** [comment]
I understood but you'll solution will break all the existing system which I don't want. You can set logic to check if the waiting logo is set or not, if not set then use it otherwise keep default. Also try to commit everything in 1 PR.

**Comment by jibon57** [comment]
@oksuzgil you can have a look this PR: https://github.com/mynaparrot/plugNmeet-client/pull/511

**Comment by oksuzgil** [comment]
Thank you very much, I actually wanted to contribute in my spare time, even if it was a little bit, even though I don't know the react side. I gave up getting involved in the process on issues I don't know :) I continue with my half-project. Apparently I tired you. Because of me, you had to do work that wasn't in your business plan.

**Pull request closed without merging**
